const req = {
  date: "Friday, 15 July 22",
  slot: "2:00 PM-2:10 PM",
  mode: "bw_call",
  brand: "BW",
  phone: "8103989510",
  email: "nileshpatidar875@gmail.com",
  patient_name: "Nilesh Patidar",
  category: ["is_hc"],
  language: "English",
  slot_time_period: 10,
  source: "DA",
  source_id: "820",
  user_id: "820",
  primary_source: "TopbarBD",
  secondary_source: "TopbarBD",
  doctor_id: "",
  FU_ques: {
    category: "Hair",
    hairCondition: "Dull and rough hair",
    anything_else: "",
    age: "21",
    weight: "23",
    height: "4' 10''",
  },
  recommended_products: [
    "hair-strengthening-serum",
    "deep-moisturizing-conditioner",
    "biotin-multivitamin-hair-gummies-2m",
  ],
  immediate: true,
};
const res = {
  doctor_name: "NA",
  doctor_email: "NA",
  id: 16206,
  appointment_date: "2022-07-22",
  schedule_token: "524967e0-ec5e-4f12-b963-b80a58a7e074",
  from_time: "18:40:14",
  to_time: "18:50:14",
  email: "nileshpatidar875@gmail.com",
  phone: "8103989510",
  brand: "BW",
  follow_up: 1,
  category: "is_hc",
  slot_start_time: "18:40",
  slot_end_time: "18:50",
  doctor_img: "NA",
  doctor_qualifications: "NA",
};
