const req = { scheduleToken: "524967e0-ec5e-4f12-b963-b80a58a7e074" };

const res = {
  success: true,
  data: {
    appointment: {
      created_dttm: "2022-07-22 13:10:14",
      updated_dttm: "2022-07-22 13:12:17",
      doctor_id: 32,
      appointment_date: "2022-07-22",
      from_time: "18:40:00",
      to_time: "18:50:00",
      name: null,
      email: "nileshpatidar875@gmail.com",
      phone: "8103989510",
      brand: "BW",
      follow_up: 1,
      id: 16206,
      category: "is_hc",
      slot_start_time: "18:40:00",
      slot_end_time: "18:50:00",
      notified: 0,
      source: "DA",
      source_id: "820",
      form_id: null,
      patient_name: "Nilesh Patidar",
      status: "s",
      form_order_placed: 0,
      order_id: null,
      rescheduled: 0,
      rescheduled_by: null,
      schedule_token: "524967e0-ec5e-4f12-b963-b80a58a7e074",
      prescription_generated: 0,
      reschedule_sent: 0,
      overbooked_flag: 0,
      on_time_flag: null,
      payment_method: null,
      on_time: 1,
      delete_flag: 0,
      FU_ques:
        '{"category":"Hair","hairCondition":"Dull and rough hair","anythingElse":"","age":"21","weight":"23","height":"4\' 10\'\'"}',
      DA_ques: null,
      MA_ques: null,
      overbook_sr_no: 0,
      image_upload_flag: 0,
      nps_score: null,
      nps_score_given_at: null,
      image_upload_notify: 0,
      prescription_order_ids: null,
      recommended_products:
        "hair-strengthening-serum,deep-moisturizing-conditioner,biotin-multivitamin-hair-gummies-2m",
      nps_suggestion: null,
      pci_Improve: null,
      slot_time_period: null,
      original_appt_date: "2022-07-22",
      missed_counted: 0,
      request_callback: null,
      request_callback_time: null,
      doctor_consulted: null,
      image_uploaded: 0,
      image_upload_reminder_sent: 0,
      call_sid_list: null,
      nps_irrelevant: 0,
      confirmed: null,
      cancelled: null,
      room_id: null,
      duration: 0,
      image_upload_requested: null,
      original_doctor_id: 32,
      order_placed: null,
      email_sent: null,
      email_sent_dttm: null,
      opt_in: null,
      followup_status: 0,
      user_id: "820",
      language: "English",
      type_of_call: null,
      repeat_customer: 0,
      optional_rx: null,
      utm_source: null,
      primary_source: "TopbarBD",
      secondary_source: "TopbarBD",
      app: null,
      mode: "bw_call",
      mismatch: null,
      paid: 0,
      system_call: 1,
      system_call_attempts: 3,
      system_call_success: 2,
      system_call_patient_success: 0,
      system_call_busy: 1,
      cron_attempts: 0,
      followup_duration: null,
      es_audio_status: "patient-missed",
      doctor_name: "Dr.Anmol",
    },
  },
};
